name: Deploy to Bunny.net

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Bunny.net
        uses: ayeressian/bunnycdn-storage-deploy@v2.2.2
        with:
          source: "src"
          destination: ""
          storageZoneName: "${{ secrets.STATIC_STORAGE_NAME }}"
          storagePassword: "${{ secrets.STATIC_STORAGE_PASSWORD }}"
          accessKey: "${{ secrets.CDN_ACCESS_KEY }}"
          pullZoneId: "${{ secrets.STATIC_PULL_ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
